"""Portable Kali validation-kit generation and evidence import.

The Windows host prepares a kit but never contacts a target.  An operator copies
the kit to Kali, reviews and runs the generated Bash scripts, then copies the
same directory back.  Captures are tied to finding ids and can be imported into
the engagement for review and final PoC export.
"""

from __future__ import annotations

import json
import re
import shlex
import shutil
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from vapt_verify.adapters import get_adapter
from vapt_verify.adapters.base import AdapterKind, ExecutionContext, RawResult
from vapt_verify.classification.classifier import Classifier
from vapt_verify.classification.models import Capabilities
from vapt_verify.models.evidence import Evidence
from vapt_verify.models.finding import Finding
from vapt_verify.models.recipe import RecipeStep
from vapt_verify.recipes.library import RecipeLibrary
from vapt_verify.utilities.hashing import sha256_file
from vapt_verify.workspace import EngagementWorkspace

KIT_SCHEMA_VERSION = "1"


@dataclass
class KitStep:
    step_id: str
    finding_id: str
    asset_id: str
    plugin_id: str
    title: str
    severity: str
    target: str
    port: int
    transport: str
    adapter: str
    tool: str
    mode: str
    description: str
    safety_class: str
    nmap_role: str
    command_args: list[str] = field(default_factory=list)
    expected_evidence: list[str] = field(default_factory=list)
    limitations: list[str] = field(default_factory=list)

    @property
    def executable(self) -> bool:
        return bool(self.command_args)

    def to_dict(self) -> dict[str, Any]:
        return {
            "step_id": self.step_id,
            "finding_id": self.finding_id,
            "asset_id": self.asset_id,
            "plugin_id": self.plugin_id,
            "title": self.title,
            "severity": self.severity,
            "target": self.target,
            "port": self.port,
            "transport": self.transport,
            "adapter": self.adapter,
            "tool": self.tool,
            "mode": self.mode,
            "description": self.description,
            "safety_class": self.safety_class,
            "nmap_role": self.nmap_role,
            "command_args": self.command_args,
            "command": shlex.join(self.command_args) if self.command_args else "",
            "expected_evidence": self.expected_evidence,
            "limitations": self.limitations,
            "executable": self.executable,
        }


@dataclass
class KitBuildResult:
    root: Path
    finding_count: int
    executable_count: int
    manual_count: int
    steps: list[KitStep]


@dataclass
class EvidenceImportSummary:
    imported: int = 0
    skipped_duplicates: int = 0
    errors: list[str] = field(default_factory=list)


class OnsiteKitBuilder:
    """Render every finding as Kali commands or an explicit manual check."""

    def __init__(self, workspace: EngagementWorkspace) -> None:
        self.ws = workspace
        self.library = RecipeLibrary.load_builtin()
        # Selection must not depend on which tools happen to exist on Windows.
        self.classifier = Classifier(self.library, Capabilities(available=set()))

    def build(self, output_dir: str | Path, *, force: bool = False) -> KitBuildResult:
        root = Path(output_dir)
        manifest_path = root / "manifest.json"
        if manifest_path.exists() and not force:
            raise FileExistsError(
                f"A validation kit already exists at {root}. Use --force to refresh its "
                "generated files; existing evidence will be preserved."
            )
        if root.exists() and any(root.iterdir()) and not manifest_path.exists() and not force:
            raise FileExistsError(
                f"Output directory {root} is not empty and is not a validation kit. "
                "Choose an empty directory."
            )
        root.mkdir(parents=True, exist_ok=True)
        scripts_dir = root / "scripts"
        scripts_dir.mkdir(exist_ok=True)
        if force:
            # Refresh only files generated by this builder. Captured evidence is
            # deliberately outside this directory and is never removed.
            for old_script in scripts_dir.glob("*.sh"):
                old_script.unlink()
        (root / "lib").mkdir(exist_ok=True)
        (root / "evidence").mkdir(exist_ok=True)

        assets = {a["asset_id"]: a for a in self.ws.load_assets()}
        findings = [Finding.from_dict(row) for row in self.ws.load_findings()]
        steps: list[KitStep] = []
        for finding in findings:
            steps.extend(self._steps_for_finding(finding, assets.get(finding.asset_id, {})))

        executable = [step for step in steps if step.executable]
        manual = [step for step in steps if not step.executable]
        manifest = {
            "kit_schema_version": KIT_SCHEMA_VERSION,
            "engagement_id": self.ws.root.name,
            "purpose": "Manual validation from Kali; generated on Windows without execution.",
            "finding_count": len(findings),
            "executable_step_count": len(executable),
            "manual_step_count": len(manual),
            "steps": [step.to_dict() for step in steps],
        }

        _write_lf(root / "manifest.json", json.dumps(manifest, indent=2, sort_keys=True) + "\n")
        _write_lf(root / "README.md", self._readme(len(findings), len(executable), len(manual)))
        _write_lf(root / "commands.md", self._commands_markdown(findings, steps))
        _write_lf(root / "lib" / "capture.sh", _capture_library())
        _write_lf(root / "run-all.sh", _run_all_script())
        for step in executable:
            _write_lf(scripts_dir / f"{step.step_id}.sh", _step_script(step))

        return KitBuildResult(
            root=root,
            finding_count=len(findings),
            executable_count=len(executable),
            manual_count=len(manual),
            steps=steps,
        )

    def _steps_for_finding(self, finding: Finding, asset: dict[str, Any]) -> list[KitStep]:
        classification = self.classifier.classify(finding)
        recipe = self.library.by_id(classification.selected_recipe_id)
        if recipe is None:
            return [self._manual_fallback(finding, asset, "No verification recipe was found.")]

        target = _target_for(finding, asset)
        hostname = _hostname_for(finding, asset)
        result: list[KitStep] = []
        ordered: list[RecipeStep] = [*recipe.automated_steps, *recipe.assisted_steps]
        for index, recipe_step in enumerate(ordered, start=1):
            params = _step_params(recipe_step, finding, hostname)
            command_args: list[str] = []
            description = recipe_step.description
            adapter = get_adapter(recipe_step.adapter)

            if recipe_step.adapter == "snmp" and not params.get("community"):
                description += (
                    " The exact community could not be extracted from Nessus; enter it "
                    "manually and do not guess or brute-force."
                )
            elif adapter is not None and adapter.kind is AdapterKind.COMMAND:
                ctx = ExecutionContext(
                    finding_id=finding.finding_id,
                    asset_id=finding.asset_id,
                    engagement_id=self.ws.root.name,
                    target=target,
                    port=finding.port,
                    transport=finding.transport.value,
                    params=params,
                )
                command_args = adapter.build_argv(ctx)
            elif (
                adapter is not None
                and adapter.kind is AdapterKind.INPROCESS
                and finding.transport.value == "tcp"
                and finding.port > 0
            ):
                # The desktop implementation uses Python sockets.  Kali gets an
                # equivalent transparent TCP-connect command instead.
                command_args = ["nc", "-vz", "-w", "5", target, str(finding.port)]

            result.append(
                KitStep(
                    step_id=_step_id(finding.finding_id, index, recipe_step.adapter),
                    finding_id=finding.finding_id,
                    asset_id=finding.asset_id,
                    plugin_id=finding.plugin_id,
                    title=finding.plugin_name,
                    severity=finding.severity.name,
                    target=target,
                    port=finding.port,
                    transport=finding.transport.value,
                    adapter=recipe_step.adapter,
                    tool=(command_args[0] if command_args else recipe_step.capability),
                    mode=recipe_step.mode.value,
                    description=description,
                    safety_class=recipe.safety_class.value,
                    nmap_role=recipe.nmap_role.value,
                    command_args=command_args,
                    expected_evidence=list(recipe.positive_evidence),
                    limitations=list(recipe.known_limitations),
                )
            )

        next_index = len(result) + 1
        for offset, recipe_step in enumerate(recipe.manual_steps):
            result.append(
                KitStep(
                    step_id=_step_id(finding.finding_id, next_index + offset, recipe_step.adapter),
                    finding_id=finding.finding_id,
                    asset_id=finding.asset_id,
                    plugin_id=finding.plugin_id,
                    title=finding.plugin_name,
                    severity=finding.severity.name,
                    target=target,
                    port=finding.port,
                    transport=finding.transport.value,
                    adapter=recipe_step.adapter,
                    tool="",
                    mode="manual",
                    description=_specific_manual_description(finding, recipe_step.description),
                    safety_class=recipe.safety_class.value,
                    nmap_role=recipe.nmap_role.value,
                    expected_evidence=list(recipe.positive_evidence),
                    limitations=list(recipe.known_limitations),
                )
            )

        if not result:
            result.append(self._manual_fallback(finding, asset, "Manual reviewer assessment."))
        return result

    def _manual_fallback(
        self, finding: Finding, asset: dict[str, Any], description: str
    ) -> KitStep:
        return KitStep(
            step_id=_step_id(finding.finding_id, 1, "manual"),
            finding_id=finding.finding_id,
            asset_id=finding.asset_id,
            plugin_id=finding.plugin_id,
            title=finding.plugin_name,
            severity=finding.severity.name,
            target=_target_for(finding, asset),
            port=finding.port,
            transport=finding.transport.value,
            adapter="manual",
            tool="",
            mode="manual",
            description=description,
            safety_class="manual",
            nmap_role="inappropriate",
        )

    def _readme(self, findings: int, executable: int, manual: int) -> str:
        return f"""# Kali validation kit

This kit contains {findings} Nessus finding(s), {executable} executable validation
step(s), and {manual} manual evidence request(s). It was generated without contacting
any target.

## On Kali

1. Read `commands.md` and confirm the listed targets are authorised.
2. Install only the tools required for the checks you intend to run.
3. Make the scripts executable: `chmod +x run-all.sh scripts/*.sh lib/capture.sh`
4. Run `./run-all.sh`. It asks before every command.
5. To run only one finding: `./run-all.sh --finding FINDING_ID`

`./run-all.sh --yes` removes the per-command prompt. Use it only after reviewing
the whole kit and confirming scope.

Captured output and metadata are written under `evidence/`. Keep the entire kit
directory together and copy it back to the Windows host. Do not edit captured files;
their SHA-256 values are verified during import.

Manual-only findings are intentional. A remote Nmap command cannot validate every
credentialed patch, host configuration, or application finding. Follow their exact
requests in `commands.md` and attach the resulting evidence separately if needed.
"""

    def _commands_markdown(self, findings: list[Finding], steps: list[KitStep]) -> str:
        by_finding: dict[str, list[KitStep]] = {}
        for step in steps:
            by_finding.setdefault(step.finding_id, []).append(step)
        lines = [
            "# Onsite validation commands",
            "",
            "> Review scope before execution. A successful command is evidence capture, "
            "not a verdict.",
            "",
        ]
        for finding in findings:
            finding_steps = by_finding.get(finding.finding_id, [])
            target = finding_steps[0].target if finding_steps else finding.asset_id
            location = (
                f"{finding.port}/{finding.transport.value}"
                if finding.port
                else "host-level (port 0)"
            )
            lines.extend(
                [
                    f"## {finding.plugin_name}",
                    "",
                    f"- Finding: `{finding.finding_id}`",
                    f"- Nessus plugin: `{finding.plugin_id or 'n/a'}`",
                    f"- Severity: {finding.severity.name}",
                    f"- Target: `{target}` ({location})",
                    "- Scanner claim: "
                    f"{finding.synopsis or finding.description or '(not provided)'}",
                    "",
                ]
            )
            for step in finding_steps:
                lines.append(f"### {step.mode}: {step.adapter}")
                lines.append("")
                lines.append(step.description)
                lines.append("")
                if step.executable:
                    lines.extend(
                        [
                            f"Script: `scripts/{step.step_id}.sh`",
                            "",
                            "```bash",
                            shlex.join(step.command_args),
                            "```",
                            "",
                        ]
                    )
                else:
                    lines.extend(
                        ["**Manual evidence required; no remote command is generated.**", ""]
                    )
                for expected in step.expected_evidence:
                    lines.append(f"- Confirming evidence: {expected}")
                for limitation in step.limitations:
                    lines.append(f"- Limitation: {limitation}")
                if step.expected_evidence or step.limitations:
                    lines.append("")
        return "\n".join(lines).rstrip() + "\n"


class OnsiteEvidenceImporter:
    """Verify and import capture files produced by a generated Kali kit."""

    def __init__(self, workspace: EngagementWorkspace) -> None:
        self.ws = workspace

    def import_kit(
        self, kit_root: str | Path, *, operator_override: str = ""
    ) -> EvidenceImportSummary:
        root = Path(kit_root)
        summary = EvidenceImportSummary()
        manifest_path = root / "manifest.json"
        if not manifest_path.exists():
            summary.errors.append(f"manifest.json not found under {root}")
            return summary
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if str(manifest.get("engagement_id", "")) != self.ws.root.name:
            summary.errors.append(
                "Kit engagement id does not match the selected engagement "
                f"({manifest.get('engagement_id')!r} != {self.ws.root.name!r})."
            )
            return summary

        evidence_dir = root / "evidence"
        if not evidence_dir.exists():
            summary.errors.append(f"evidence directory not found under {root}")
            return summary
        known_findings = {row["finding_id"]: row for row in self.ws.load_findings()}
        existing_capture_ids = {
            str((e.get("parsed_observations") or {}).get("capture_id", ""))
            for e in self.ws.load_evidence()
        }
        metadata_files = sorted(evidence_dir.glob("*.json"))
        if not metadata_files:
            summary.errors.append("No captured evidence metadata was found in evidence/.")
            return summary

        for metadata_path in metadata_files:
            try:
                metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
                self._import_one(
                    root,
                    metadata,
                    known_findings,
                    existing_capture_ids,
                    operator_override,
                    summary,
                )
            except (OSError, ValueError, TypeError, json.JSONDecodeError) as exc:
                summary.errors.append(f"{metadata_path.name}: {exc}")
        return summary

    def _import_one(
        self,
        root: Path,
        metadata: dict[str, Any],
        known_findings: dict[str, dict[str, Any]],
        existing_capture_ids: set[str],
        operator_override: str,
        summary: EvidenceImportSummary,
    ) -> None:
        if str(metadata.get("kit_schema_version", "")) != KIT_SCHEMA_VERSION:
            raise ValueError("unsupported or missing kit_schema_version")
        finding_id = str(metadata.get("finding_id", ""))
        row = known_findings.get(finding_id)
        if row is None:
            raise ValueError(f"unknown finding id {finding_id!r}")
        capture_id = str(metadata.get("capture_id", ""))
        if not capture_id:
            raise ValueError("capture_id is missing")
        if capture_id in existing_capture_ids:
            summary.skipped_duplicates += 1
            return

        relative_output = Path(str(metadata.get("output_file", "")))
        output_path = (root / relative_output).resolve()
        root_resolved = root.resolve()
        if not output_path.is_relative_to(root_resolved):
            raise ValueError("output_file points outside the kit")
        if not output_path.is_file():
            raise ValueError(f"captured output is missing: {relative_output}")
        recorded_hash = str(metadata.get("sha256", ""))
        actual_hash = sha256_file(output_path)
        if not recorded_hash or actual_hash != recorded_hash:
            raise ValueError("captured output SHA-256 does not match metadata")

        command_args = metadata.get("command_args", [])
        if not isinstance(command_args, list) or not all(isinstance(a, str) for a in command_args):
            raise ValueError("command_args must be a list of strings")
        output = output_path.read_text(encoding="utf-8", errors="replace")
        adapter_name = str(metadata.get("adapter", "external"))
        timed_out = bool(metadata.get("timed_out", False))
        exit_code_raw = metadata.get("exit_code")
        exit_code = int(exit_code_raw) if exit_code_raw is not None else None
        observations: dict[str, Any] = {
            "capture_id": capture_id,
            "kit_step_id": metadata.get("step_id", ""),
        }
        review_note = "Imported from a Kali validation kit; reviewer interpretation required."
        adapter = get_adapter(adapter_name)
        if adapter is not None:
            ctx = ExecutionContext(
                finding_id=finding_id,
                asset_id=row["asset_id"],
                engagement_id=self.ws.root.name,
                target=str(metadata.get("target", "")),
                port=int(metadata.get("port", row.get("port", 0)) or 0),
                transport=str(metadata.get("transport", row.get("transport", ""))),
            )
            raw = RawResult(exit_code=exit_code, stdout=output, timed_out=timed_out)
            if adapter_name == "tcp":
                lowered = output.lower()
                raw.port_open = "succeeded" in lowered or "open" in lowered
            parsed = adapter.parse(ctx, raw)
            observations.update(parsed.observations)
            if parsed.note:
                review_note = parsed.note

        evidence_id = uuid.uuid4().hex
        dest_dir = self.ws.evidence_dir / row["asset_id"] / finding_id
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest = dest_dir / f"kali_{evidence_id[:8]}_{output_path.name}"
        shutil.copy2(output_path, dest)
        evidence = Evidence(
            evidence_id=evidence_id,
            finding_id=finding_id,
            engagement_id=self.ws.root.name,
            asset_id=row["asset_id"],
            adapter=adapter_name,
            tool_name=str(metadata.get("tool_name") or adapter_name),
            tool_version=str(metadata.get("tool_version", "")),
            command_args=list(command_args),
            sanitized_command=shlex.join(command_args),
            operator=operator_override or str(metadata.get("operator", "unknown")),
            start_timestamp=str(metadata.get("start_timestamp", "")),
            end_timestamp=str(metadata.get("end_timestamp", "")),
            exit_code=exit_code,
            timed_out=timed_out,
            stdout=output[:20000],
            parsed_observations=observations,
            raw_evidence_path=str(dest),
            sha256=actual_hash,
            sanitization_status="kali_capture_unsanitized",
            review_notes=review_note,
        )
        self.ws.append_evidence(evidence.to_dict())
        self.ws.append_audit_event(
            {
                "event": "kali_evidence_import",
                "finding_id": finding_id,
                "evidence_id": evidence_id,
                "capture_id": capture_id,
                "operator": evidence.operator,
            }
        )
        existing_capture_ids.add(capture_id)
        summary.imported += 1


def _target_for(finding: Finding, asset: dict[str, Any]) -> str:
    raw_ip = finding.host_properties.get("host-ip")
    if isinstance(raw_ip, list):
        raw_ip = raw_ip[0] if raw_ip else ""
    if raw_ip:
        return str(raw_ip)
    addresses = asset.get("ip_addresses", [])
    if addresses:
        return str(addresses[0])
    return str(asset.get("primary_key") or finding.asset_id)


def _hostname_for(finding: Finding, asset: dict[str, Any]) -> str:
    for value in [*asset.get("fqdns", []), *asset.get("hostnames", [])]:
        if value:
            return str(value)
    for key in ("host-fqdn", "host-rdns", "netbios-name"):
        value = finding.host_properties.get(key)
        if isinstance(value, list):
            value = value[0] if value else ""
        if value:
            return str(value)
    return ""


def _step_params(step: RecipeStep, finding: Finding, hostname: str) -> dict[str, Any]:
    params = dict(step.params)
    if hostname:
        params.setdefault("vhost", hostname)
    if params.get("starttls_from"):
        service = finding.service.lower()
        for candidate in ("smtp", "imap", "pop3", "ftp", "xmpp"):
            if candidate in service:
                params["starttls"] = candidate
                break
    if step.adapter == "snmp":
        community = _extract_snmp_community(finding)
        if community:
            params["community"] = community
    return params


def _extract_snmp_community(finding: Finding) -> str:
    text = f"{finding.plugin_name}\n{finding.plugin_output}"
    patterns = [
        r"community string\s*:\s*([^\s,;]+)",
        r"community name\s*:\s*([^\s,;]+)",
        r"community[^\n]*(?:is|was)\s+['\"]?([^\s'\",;]+)",
        r"\(([^()\s]+)\)\s*$",
    ]
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE | re.MULTILINE)
        if match:
            value = match.group(1).strip("'\".()[]")
            if value:
                return value
    return ""


def _specific_manual_description(finding: Finding, description: str) -> str:
    if finding.is_host_level and "ubuntu" in finding.plugin_family.lower():
        package_match = re.search(
            r"Remote package installed\s*:\s*([A-Za-z0-9.+-]+?)(?:_|\s)",
            finding.plugin_output,
            flags=re.IGNORECASE,
        )
        package = package_match.group(1) if package_match else "the reported package"
        return (
            f"{description} On the affected host, have an authorised administrator run "
            f"`dpkg-query -W -f='${{Package}}\\t${{Version}}\\n' {package}` and capture "
            "the output. Compare the installed version with the fixed version in the Nessus output."
        )
    return description


def _step_id(finding_id: str, index: int, adapter: str) -> str:
    clean_finding = re.sub(r"[^A-Za-z0-9_.-]", "_", finding_id)
    clean_adapter = re.sub(r"[^A-Za-z0-9_.-]", "_", adapter)
    return f"{clean_finding}__{index:02d}_{clean_adapter}"


def _write_lf(path: Path, content: str) -> None:
    # Bash shebangs copied from Windows must use LF or Kali reads "bash\r".
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def _bash(value: str) -> str:
    return shlex.quote(value)


def _step_script(step: KitStep) -> str:
    args = " ".join(_bash(arg) for arg in step.command_args)
    fields = [
        step.step_id,
        step.finding_id,
        step.asset_id,
        step.adapter,
        step.tool,
        step.target,
        str(step.port),
        step.transport,
        step.title,
        step.description,
    ]
    separator = " " + chr(92) + "\n  "
    rendered_fields = separator.join(_bash(value) for value in fields)
    return f"""#!/usr/bin/env bash
set -uo pipefail

KIT_ROOT="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/.." && pwd)"
export KIT_ROOT
# shellcheck source=../lib/capture.sh
source "$KIT_ROOT/lib/capture.sh"

capture_step \\
  {rendered_fields} \\
  -- {args}
"""


def _run_all_script() -> str:
    return """#!/usr/bin/env bash
set -uo pipefail

KIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
finding_filter=""
for arg in "$@"; do
  case "$arg" in
    --yes) export VAPT_APPROVE_ALL=1 ;;
    --finding=*) finding_filter="${arg#--finding=}" ;;
  esac
done
if [[ "${1:-}" == "--finding" && -n "${2:-}" ]]; then
  finding_filter="$2"
fi

found=0
for script in "$KIT_ROOT"/scripts/*.sh; do
  [[ -e "$script" ]] || continue
  if [[ -n "$finding_filter" && "$(basename "$script")" != "$finding_filter"__* ]]; then
    continue
  fi
  found=1
  bash "$script"
done

if [[ $found -eq 0 ]]; then
  echo "No executable scripts matched. Review commands.md for manual evidence requests."
fi
echo "Done. Keep the entire kit and copy it back for evidence import."
"""


def _capture_library() -> str:
    return r'''#!/usr/bin/env bash
# Shared evidence-capture function. Generated scripts pass commands as arrays;
# no eval or shell-expanded command string is used.

capture_step() {
  local step_id="$1" finding_id="$2" asset_id="$3" adapter="$4" tool_name="$5"
  local target="$6" port="$7" transport="$8" title="$9" description="${10}"
  shift 10
  [[ "${1:-}" == "--" ]] && shift
  local -a command_argv=("$@")

  echo
  echo "[$finding_id] $title"
  echo "Target: $target  Port: $port/$transport"
  echo "Purpose: $description"
  printf 'Command:'
  printf ' %q' "${command_argv[@]}"
  echo

  if [[ "${VAPT_APPROVE_ALL:-0}" != "1" ]]; then
    read -r -p "Run this authorised validation? [y/N/q] " answer
    case "${answer,,}" in
      y|yes) ;;
      q|quit) echo "Stopped by operator."; exit 0 ;;
      *) echo "Skipped."; return 0 ;;
    esac
  fi

  if ! command -v "${command_argv[0]}" >/dev/null 2>&1; then
    echo "SKIPPED: required tool not found: ${command_argv[0]}"
    return 0
  fi
  for required in python3 sha256sum tee timeout; do
    if ! command -v "$required" >/dev/null 2>&1; then
      echo "ERROR: capture dependency not found: $required"
      return 1
    fi
  done

  local evidence_dir="$KIT_ROOT/evidence"
  mkdir -p "$evidence_dir"
  local stamp capture_id output_path metadata_path
  stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  capture_id="${step_id}_${stamp}_${BASHPID}"
  output_path="$evidence_dir/${capture_id}.txt"
  metadata_path="$evidence_dir/${capture_id}.json"
  local start end exit_code timed_out sha tool_version timeout_seconds
  start="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  timeout_seconds="${VAPT_TIMEOUT_SECONDS:-120}"
  tool_version="$(timeout 5 "${command_argv[0]}" --version 2>&1 | head -n 1 || true)"

  set +e
  timeout --signal=INT "$timeout_seconds" "${command_argv[@]}" </dev/null 2>&1 | tee "$output_path"
  exit_code=${PIPESTATUS[0]}
  set -e
  end="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  timed_out=false
  [[ $exit_code -eq 124 || $exit_code -eq 137 ]] && timed_out=true
  sha="$(sha256sum "$output_path" | awk '{print $1}')"

  python3 - "$metadata_path" "$KIT_ROOT" "$output_path" "$sha" "$capture_id" \
    "$step_id" "$finding_id" "$asset_id" "$adapter" "$tool_name" "$tool_version" \
    "$target" "$port" "$transport" "${USER:-unknown}" "$start" "$end" \
    "$exit_code" "$timed_out" "${command_argv[@]}" <<'PY'
import json
import os
import shlex
import sys

(
    metadata_path, kit_root, output_path, digest, capture_id, step_id,
    finding_id, asset_id, adapter, tool_name, tool_version, target, port,
    transport, operator, start, end, exit_code, timed_out, *command_args
) = sys.argv[1:]
payload = {
    "kit_schema_version": "1",
    "capture_id": capture_id,
    "step_id": step_id,
    "finding_id": finding_id,
    "asset_id": asset_id,
    "adapter": adapter,
    "tool_name": tool_name,
    "tool_version": tool_version,
    "target": target,
    "port": int(port),
    "transport": transport,
    "operator": operator,
    "start_timestamp": start,
    "end_timestamp": end,
    "exit_code": int(exit_code),
    "timed_out": timed_out.lower() == "true",
    "command_args": command_args,
    "command": shlex.join(command_args),
    "output_file": os.path.relpath(output_path, kit_root),
    "sha256": digest,
}
with open(metadata_path, "w", encoding="utf-8", newline="\n") as handle:
    json.dump(payload, handle, indent=2, sort_keys=True)
    handle.write("\n")
PY

  echo "Captured: $output_path"
  echo "SHA-256: $sha"
  echo "Exit code $exit_code is execution status only; it is not a vulnerability verdict."
  set +e
  return 0
}
'''
