"""Portable Kali validation-kit generation and evidence import.

The Windows host prepares a kit but never contacts a target.  An operator copies
the kit to Kali, reviews and runs the generated Bash scripts, then copies the
same directory back.  Captures are tied to finding ids and can be imported into
the engagement for review and final PoC export.
"""

from __future__ import annotations

import json
import re
import shlex
import shutil
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from vapt_verify.adapters import get_adapter
from vapt_verify.adapters.base import AdapterKind, ExecutionContext, RawResult
from vapt_verify.classification.classifier import Classifier
from vapt_verify.classification.models import Capabilities
from vapt_verify.models.enums import Severity
from vapt_verify.models.evidence import Evidence
from vapt_verify.models.finding import Finding
from vapt_verify.models.recipe import RecipeStep
from vapt_verify.naming import finding_basename
from vapt_verify.recipes.library import RecipeLibrary
from vapt_verify.security.scope import ScopeEnforcer, is_valid_target
from vapt_verify.utilities.hashing import sha256_file
from vapt_verify.workspace import EngagementWorkspace

KIT_SCHEMA_VERSION = "2"

#: Capture metadata this build can still import.
#:
#: Version 2 only *added* fields (scope labelling), so a kit generated by an
#: earlier build captures evidence this build reads perfectly well. An operator
#: who upgrades between preparing a kit and importing it back must not find
#: their field evidence rejected over a version integer.
SUPPORTED_CAPTURE_SCHEMA_VERSIONS = frozenset({"1", "2"})

#: Scope labels carried by every generated step.
#:
#: The kit is prepared on a machine that never contacts a target, so scope
#: cannot *gate* generation the way it gates execution -- and an engagement
#: whose scope has not been filled in yet must still produce a usable kit
#: rather than an empty one. Scope therefore labels each step, and `run-all.sh`
#: refuses to execute anything explicitly out of scope.
SCOPE_IN_SCOPE = "in_scope"
SCOPE_OUT_OF_SCOPE = "out_of_scope"
SCOPE_UNCONFIGURED = "scope_unconfigured"
SCOPE_UNUSABLE_TARGET = "unusable_target"


@dataclass
class KitStep:
    step_id: str
    finding_id: str
    asset_id: str
    plugin_id: str
    title: str
    severity: str
    target: str
    port: int
    transport: str
    adapter: str
    tool: str
    mode: str
    description: str
    safety_class: str
    nmap_role: str
    command_args: list[str] = field(default_factory=list)
    #: What in the captured output would confirm the scanner's claim.
    expected_evidence: list[str] = field(default_factory=list)
    #: What would *contradict* it. Carried because the alternative is an
    #: operator reading "no output" as "not vulnerable" -- an inference this
    #: tool must never invite. Absence of the confirming signal is only
    #: meaningful if the operator knows what refutation actually looks like.
    refuting_evidence: list[str] = field(default_factory=list)
    #: Conditions under which the capture proves nothing either way.
    inconclusive_conditions: list[str] = field(default_factory=list)
    limitations: list[str] = field(default_factory=list)
    #: Authorisation status of this step's target, as the engagement declares it.
    #: Generating a command is not running it, so scope does not *suppress* a
    #: step -- it labels one, and the runner refuses to execute anything not
    #: marked in-scope without an explicit override.
    scope_status: str = SCOPE_UNCONFIGURED
    scope_reason: str = ""

    @property
    def executable(self) -> bool:
        return bool(self.command_args)

    @property
    def authorised(self) -> bool:
        """Whether run-all.sh will execute this step without an override."""
        return self.scope_status in {SCOPE_IN_SCOPE, SCOPE_UNCONFIGURED}

    def to_dict(self) -> dict[str, Any]:
        return {
            "step_id": self.step_id,
            "finding_id": self.finding_id,
            "asset_id": self.asset_id,
            "plugin_id": self.plugin_id,
            "title": self.title,
            "severity": self.severity,
            "target": self.target,
            "port": self.port,
            "transport": self.transport,
            "adapter": self.adapter,
            "tool": self.tool,
            "mode": self.mode,
            "description": self.description,
            "safety_class": self.safety_class,
            "nmap_role": self.nmap_role,
            "command_args": self.command_args,
            "command": shlex.join(self.command_args) if self.command_args else "",
            "expected_evidence": self.expected_evidence,
            "refuting_evidence": self.refuting_evidence,
            "inconclusive_conditions": self.inconclusive_conditions,
            "limitations": self.limitations,
            "executable": self.executable,
            "scope_status": self.scope_status,
            "scope_reason": self.scope_reason,
            "authorised": self.authorised,
        }


@dataclass
class KitBuildResult:
    root: Path
    finding_count: int
    executable_count: int
    manual_count: int
    steps: list[KitStep]
    #: Whether the engagement declared an approved scope at all. False means the
    #: kit could not check any target, which the operator has to be told.
    scope_configured: bool = True
    #: Steps whose target the engagement explicitly does not cover. Generated,
    #: labelled, and refused at run time -- never silently dropped.
    out_of_scope_count: int = 0
    #: Steps whose scan-reported target is not a usable address, so no command
    #: could be addressed to it.
    unusable_target_count: int = 0


@dataclass
class EvidenceImportSummary:
    imported: int = 0
    skipped_duplicates: int = 0
    errors: list[str] = field(default_factory=list)


class OnsiteKitBuilder:
    """Render every finding as Kali commands or an explicit manual check."""

    def __init__(self, workspace: EngagementWorkspace) -> None:
        self.ws = workspace
        self.library = RecipeLibrary.load_builtin()
        # Selection must not depend on which tools happen to exist on Windows.
        self.classifier = Classifier(self.library, Capabilities(available=set()))
        engagement = workspace.engagement()
        self._enforcer = ScopeEnforcer(engagement)
        self._scope_configured = bool(
            engagement.approved_cidrs
            or engagement.approved_targets
            or engagement.approved_hostnames
        )

    def _scope_for(self, target: str) -> tuple[str, str]:
        """Label a target's authorisation status. Never suppresses a finding.

        Three outcomes matter to the operator, and they are genuinely different:
        the target is authorised; the engagement has not declared a scope so the
        tool cannot confirm anything; or the engagement declared one and this
        target is outside it. A fourth -- the scan field is not a usable address
        at all -- stops a command being generated in the first place.
        """
        if not target or not is_valid_target(target):
            return SCOPE_UNUSABLE_TARGET, (
                f"{target!r} is not a valid IP address or hostname, so no command can "
                "be addressed to it. Resolve the address before verifying this finding."
            )
        decision = self._enforcer.validate(target)
        if decision.in_scope:
            return SCOPE_IN_SCOPE, decision.reason
        if not self._scope_configured:
            return SCOPE_UNCONFIGURED, (
                "This engagement declares no approved scope, so authorisation cannot be "
                "confirmed by the tool. Confirm the target is in scope before running."
            )
        return SCOPE_OUT_OF_SCOPE, decision.reason

    def build(
        self,
        output_dir: str | Path,
        *,
        force: bool = False,
        include_informational: bool = False,
        only_finding_ids: set[str] | None = None,
        selection_summary: str = "",
    ) -> KitBuildResult:
        root = Path(output_dir)
        manifest_path = root / "manifest.json"
        if manifest_path.exists() and not force:
            raise FileExistsError(
                f"A validation kit already exists at {root}. Use --force to refresh its "
                "generated files; existing evidence will be preserved."
            )
        if root.exists() and any(root.iterdir()) and not manifest_path.exists() and not force:
            raise FileExistsError(
                f"Output directory {root} is not empty and is not a validation kit. "
                "Choose an empty directory."
            )
        root.mkdir(parents=True, exist_ok=True)
        scripts_dir = root / "scripts"
        scripts_dir.mkdir(exist_ok=True)
        if force:
            # Refresh only files generated by this builder. Captured evidence is
            # deliberately outside this directory and is never removed.
            for old_script in scripts_dir.glob("*.sh"):
                old_script.unlink()
        (root / "lib").mkdir(exist_ok=True)
        (root / "evidence").mkdir(exist_ok=True)

        assets = {a["asset_id"]: a for a in self.ws.load_assets()}
        imported = [Finding.from_dict(row) for row in self.ws.load_findings()]
        # A selection narrows what gets a script. It never removes a finding from
        # the engagement, so the count that was left out is carried into the kit
        # and stated in its README rather than quietly vanishing.
        findings = (
            [f for f in imported if f.finding_id in only_finding_ids]
            if only_finding_ids is not None
            else imported
        )
        deselected = len(imported) - len(findings)
        # Informational findings report state, not a condition to confirm, so no
        # validation script is generated for them by default. They are still
        # listed in commands.md and counted here -- carried, not dropped.
        retained = [
            f for f in findings
            if f.severity is Severity.INFORMATIONAL and not include_informational
        ]
        retained_ids = {f.finding_id for f in retained}
        steps: list[KitStep] = []
        for finding in findings:
            if finding.finding_id in retained_ids:
                continue
            steps.extend(self._steps_for_finding(finding, assets.get(finding.asset_id, {})))

        executable = [step for step in steps if step.executable]
        manual = [step for step in steps if not step.executable]
        out_of_scope = [s for s in steps if s.scope_status == SCOPE_OUT_OF_SCOPE]
        unusable = [s for s in steps if s.scope_status == SCOPE_UNUSABLE_TARGET]
        manifest = {
            "kit_schema_version": KIT_SCHEMA_VERSION,
            "scope_configured": self._scope_configured,
            "out_of_scope_step_count": len(out_of_scope),
            "unusable_target_step_count": len(unusable),
            "engagement_id": self.ws.root.name,
            "purpose": "Manual validation from Kali; generated on Windows without execution.",
            "finding_count": len(findings),
            "imported_finding_count": len(imported),
            "deselected_finding_count": deselected,
            "selection_summary": selection_summary,
            "executable_step_count": len(executable),
            "manual_step_count": len(manual),
            "retained_informational_count": len(retained),
            "retained_informational": [
                {
                    "finding_id": f.finding_id,
                    "plugin_id": f.plugin_id,
                    "title": f.plugin_name,
                    "port": f.port,
                    "transport": f.transport.value,
                }
                for f in retained
            ],
            "steps": [step.to_dict() for step in steps],
        }

        _write_lf(root / "manifest.json", json.dumps(manifest, indent=2, sort_keys=True) + "\n")
        _write_lf(
            root / "README.md",
            self._readme(
                len(findings), len(executable), len(manual), len(retained),
                deselected=deselected, selection_summary=selection_summary,
            ),
        )
        _write_lf(root / "commands.md", self._commands_markdown(findings, steps, retained))
        _write_lf(root / "lib" / "capture.sh", _capture_library())
        _write_lf(root / "run-all.sh", _run_all_script())
        for step in executable:
            _write_lf(scripts_dir / script_filename(step), _step_script(step))

        return KitBuildResult(
            root=root,
            finding_count=len(findings),
            executable_count=len(executable),
            manual_count=len(manual),
            steps=steps,
            scope_configured=self._scope_configured,
            out_of_scope_count=len(out_of_scope),
            unusable_target_count=len(unusable),
        )

    def _steps_for_finding(self, finding: Finding, asset: dict[str, Any]) -> list[KitStep]:
        classification = self.classifier.classify(finding)
        recipe = self.library.by_id(classification.selected_recipe_id)
        if recipe is None:
            return [self._manual_fallback(finding, asset, "No verification recipe was found.")]

        target = _target_for(finding, asset)
        hostname = _hostname_for(finding, asset)
        scope_status, scope_reason = self._scope_for(target)
        result: list[KitStep] = []
        ordered: list[RecipeStep] = [*recipe.automated_steps, *recipe.assisted_steps]
        for index, recipe_step in enumerate(ordered, start=1):
            params = _step_params(recipe_step, finding, hostname)
            command_args: list[str] = []
            description = recipe_step.description
            adapter = get_adapter(recipe_step.adapter)

            if scope_status == SCOPE_UNUSABLE_TARGET:
                # A scan field that is not a valid IP or hostname must never be
                # rendered into a script an operator runs as root. It becomes a
                # manual task carrying the reason instead.
                description = (
                    f"{description} NO COMMAND GENERATED: {scope_reason}"
                ).strip()
            elif recipe_step.adapter == "snmp" and not params.get("community"):
                description += (
                    " The exact community could not be extracted from Nessus; enter it "
                    "manually and do not guess or brute-force."
                )
            elif adapter is not None and adapter.kind is AdapterKind.COMMAND:
                ctx = ExecutionContext(
                    finding_id=finding.finding_id,
                    asset_id=finding.asset_id,
                    engagement_id=self.ws.root.name,
                    target=target,
                    port=finding.port,
                    transport=finding.transport.value,
                    params=params,
                )
                command_args = adapter.build_argv(ctx)
            elif (
                adapter is not None
                and adapter.kind is AdapterKind.INPROCESS
                and finding.transport.value == "tcp"
                and finding.port > 0
            ):
                # The desktop implementation uses Python sockets.  Kali gets an
                # equivalent transparent TCP-connect command instead.
                command_args = ["nc", "-vz", "-w", "5", target, str(finding.port)]

            result.append(
                KitStep(
                    step_id=_step_id(finding.finding_id, index, recipe_step.adapter),
                    finding_id=finding.finding_id,
                    asset_id=finding.asset_id,
                    plugin_id=finding.plugin_id,
                    title=finding.plugin_name,
                    severity=finding.severity.name,
                    target=target,
                    port=finding.port,
                    transport=finding.transport.value,
                    adapter=recipe_step.adapter,
                    tool=(command_args[0] if command_args else recipe_step.capability),
                    mode=recipe_step.mode.value,
                    description=description,
                    safety_class=recipe.safety_class.value,
                    nmap_role=recipe.nmap_role.value,
                    command_args=command_args,
                    expected_evidence=list(recipe.positive_evidence),
                    refuting_evidence=list(recipe.negative_evidence),
                    inconclusive_conditions=list(recipe.inconclusive_conditions),
                    limitations=list(recipe.known_limitations),
                    scope_status=scope_status,
                    scope_reason=scope_reason,
                )
            )

        next_index = len(result) + 1
        for offset, recipe_step in enumerate(recipe.manual_steps):
            result.append(
                KitStep(
                    step_id=_step_id(finding.finding_id, next_index + offset, recipe_step.adapter),
                    finding_id=finding.finding_id,
                    asset_id=finding.asset_id,
                    plugin_id=finding.plugin_id,
                    title=finding.plugin_name,
                    severity=finding.severity.name,
                    target=target,
                    port=finding.port,
                    transport=finding.transport.value,
                    adapter=recipe_step.adapter,
                    tool="",
                    mode="manual",
                    description=_specific_manual_description(finding, recipe_step.description),
                    safety_class=recipe.safety_class.value,
                    nmap_role=recipe.nmap_role.value,
                    scope_status=scope_status,
                    scope_reason=scope_reason,
                    expected_evidence=list(recipe.positive_evidence),
                    refuting_evidence=list(recipe.negative_evidence),
                    inconclusive_conditions=list(recipe.inconclusive_conditions),
                    limitations=list(recipe.known_limitations),
                )
            )

        if not result:
            result.append(self._manual_fallback(finding, asset, "Manual reviewer assessment."))
        return result

    def _manual_fallback(
        self, finding: Finding, asset: dict[str, Any], description: str
    ) -> KitStep:
        target = _target_for(finding, asset)
        scope_status, scope_reason = self._scope_for(target)
        return KitStep(
            step_id=_step_id(finding.finding_id, 1, "manual"),
            finding_id=finding.finding_id,
            asset_id=finding.asset_id,
            plugin_id=finding.plugin_id,
            title=finding.plugin_name,
            severity=finding.severity.name,
            target=target,
            port=finding.port,
            transport=finding.transport.value,
            adapter="manual",
            tool="",
            mode="manual",
            description=description,
            safety_class="manual",
            nmap_role="inappropriate",
            scope_status=scope_status,
            scope_reason=scope_reason,
        )

    def _readme(
        self,
        findings: int,
        executable: int,
        manual: int,
        retained: int = 0,
        *,
        deselected: int = 0,
        selection_summary: str = "",
    ) -> str:
        selection = (
            f"\n## Scope of this kit\n\n{selection_summary or ''}\n"
            f"\n{deselected} imported finding(s) were deselected and have no scripts here.\n"
            "They remain in the engagement, are not false positives, and still require a\n"
            "disposition. `vapt-verify coverage` reports against every imported finding.\n"
            if deselected
            else ""
        )
        informational = (
            f"\n{retained} informational finding(s) are listed in `commands.md` under "
            "\"Retained, not scanned\" with no validation script. They report inventory or\n"
            "context rather than a condition to confirm. They remain in the engagement and\n"
            "still need a disposition at review time; rebuild with `--include-informational`\n"
            "to generate commands for them.\n"
            if retained
            else ""
        )
        return f"""# Kali validation kit

This kit contains {findings} Nessus finding(s), {executable} executable validation
step(s), and {manual} manual evidence request(s). It was generated without contacting
any target.
{selection}{informational}

## On Kali

1. Read `commands.md` and confirm the listed targets are authorised.
2. Install only the tools required for the checks you intend to run.
3. Make the scripts executable: `chmod +x run-all.sh scripts/*.sh lib/capture.sh`
4. Run `./run-all.sh`. It asks before every command.
5. To run only one finding: `./run-all.sh --finding FINDING_ID`

`./run-all.sh --yes` removes the per-command prompt. Use it only after reviewing
the whole kit and confirming scope.

Captured output and metadata are written under `evidence/`. Keep the entire kit
directory together and copy it back to the Windows host. Do not edit captured files;
their SHA-256 values are verified during import.

Manual-only findings are intentional. A remote Nmap command cannot validate every
credentialed patch, host configuration, or application finding. Follow their exact
requests in `commands.md` and attach the resulting evidence separately if needed.
"""

    def _commands_markdown(
        self,
        findings: list[Finding],
        steps: list[KitStep],
        retained: list[Finding] | None = None,
    ) -> str:
        by_finding: dict[str, list[KitStep]] = {}
        for step in steps:
            by_finding.setdefault(step.finding_id, []).append(step)
        retained = retained or []
        retained_ids = {f.finding_id for f in retained}
        lines = [
            "# Onsite validation commands",
            "",
            "> Review scope before execution. A successful command is evidence capture, "
            "not a verdict.",
            "",
        ]
        if not self._scope_configured:
            lines.extend([
                "> **This engagement declares no approved scope.** Every target below is "
                "unverified by the tool. Confirm each one is covered by your written "
                "authorisation before running anything. Set `approved_cidrs`, "
                "`approved_targets` or `approved_hostnames` in the engagement's "
                "`engagement.yaml` to have the kit check this for you.",
                "",
            ])
        for finding in findings:
            if finding.finding_id in retained_ids:
                continue
            finding_steps = by_finding.get(finding.finding_id, [])
            target = finding_steps[0].target if finding_steps else finding.asset_id
            location = (
                f"{finding.port}/{finding.transport.value}"
                if finding.port
                else "host-level (port 0)"
            )
            lines.extend(
                [
                    f"## {finding.plugin_name}",
                    "",
                    f"- Finding: `{finding.finding_id}`",
                    f"- Nessus plugin: `{finding.plugin_id or 'n/a'}`",
                    f"- Severity: {finding.severity.name}",
                    f"- Target: `{target}` ({location})",
                    "- Scanner claim: "
                    f"{finding.synopsis or finding.description or '(not provided)'}",
                    "",
                ]
            )
            scope_note = _scope_note(finding_steps)
            if scope_note:
                lines.extend([scope_note, ""])
            for step in finding_steps:
                lines.append(f"### {step.mode}: {step.adapter}")
                lines.append("")
                lines.append(step.description)
                lines.append("")
                if step.executable:
                    lines.extend(
                        [
                            f"Script: `scripts/{script_filename(step)}`",
                            "",
                            "```bash",
                            shlex.join(step.command_args),
                            "```",
                            "",
                        ]
                    )
                else:
                    lines.extend(
                        ["**Manual evidence required; no remote command is generated.**", ""]
                    )
                # Confirming and refuting evidence are listed together and
                # deliberately in that order. An operator who only knows what
                # confirms a finding will read an empty capture as a refutation,
                # which is the single inference this tool exists to prevent.
                for label, values in (
                    ("Confirms the finding", step.expected_evidence),
                    ("Contradicts the finding", step.refuting_evidence),
                    ("Inconclusive if", step.inconclusive_conditions),
                    ("Known limitation", step.limitations),
                ):
                    for value in values:
                        lines.append(f"- {label}: {value}")
                if (
                    step.expected_evidence
                    or step.refuting_evidence
                    or step.inconclusive_conditions
                    or step.limitations
                ):
                    lines.append("")
                if step.expected_evidence and not step.refuting_evidence:
                    lines.extend([
                        "- Contradicts the finding: this recipe declares no refuting "
                        "signal, so an absent confirmation is **inconclusive**, not a "
                        "clean result. Record it as needing review.",
                        "",
                    ])

        if retained:
            lines.extend([
                f"## Retained, not scanned ({len(retained)} informational)",
                "",
                "Reported for inventory and context rather than as a condition to confirm,",
                "so no validation script was generated. They remain in the engagement and",
                "still require a disposition at review time. Rebuild the kit with",
                "`--include-informational` to generate commands for them.",
                "",
                "| Severity | Target | Finding | Plugin |",
                "| --- | --- | --- | --- |",
            ])
            for finding in retained:
                location = (
                    f"{finding.port}/{finding.transport.value}"
                    if finding.port
                    else "host-level"
                )
                lines.append(
                    f"| {finding.severity.name} | `{location}` | {finding.plugin_name} "
                    f"| {finding.plugin_id or 'n/a'} |"
                )
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"


class OnsiteEvidenceImporter:
    """Verify and import capture files produced by a generated Kali kit."""

    def __init__(self, workspace: EngagementWorkspace) -> None:
        self.ws = workspace

    def import_kit(
        self, kit_root: str | Path, *, operator_override: str = ""
    ) -> EvidenceImportSummary:
        root = Path(kit_root)
        summary = EvidenceImportSummary()
        manifest_path = root / "manifest.json"
        if not manifest_path.exists():
            summary.errors.append(f"manifest.json not found under {root}")
            return summary
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if str(manifest.get("engagement_id", "")) != self.ws.root.name:
            summary.errors.append(
                "Kit engagement id does not match the selected engagement "
                f"({manifest.get('engagement_id')!r} != {self.ws.root.name!r})."
            )
            return summary

        evidence_dir = root / "evidence"
        if not evidence_dir.exists():
            summary.errors.append(f"evidence directory not found under {root}")
            return summary
        known_findings = {row["finding_id"]: row for row in self.ws.load_findings()}
        existing_capture_ids = {
            str((e.get("parsed_observations") or {}).get("capture_id", ""))
            for e in self.ws.load_evidence()
        }
        metadata_files = sorted(evidence_dir.glob("*.json"))
        if not metadata_files:
            summary.errors.append("No captured evidence metadata was found in evidence/.")
            return summary

        for metadata_path in metadata_files:
            try:
                metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
                self._import_one(
                    root,
                    metadata,
                    known_findings,
                    existing_capture_ids,
                    operator_override,
                    summary,
                )
            except (OSError, ValueError, TypeError, json.JSONDecodeError) as exc:
                summary.errors.append(f"{metadata_path.name}: {exc}")
        return summary

    def _import_one(
        self,
        root: Path,
        metadata: dict[str, Any],
        known_findings: dict[str, dict[str, Any]],
        existing_capture_ids: set[str],
        operator_override: str,
        summary: EvidenceImportSummary,
    ) -> None:
        schema = str(metadata.get("kit_schema_version", ""))
        if schema not in SUPPORTED_CAPTURE_SCHEMA_VERSIONS:
            supported = ", ".join(sorted(SUPPORTED_CAPTURE_SCHEMA_VERSIONS))
            raise ValueError(
                f"unsupported or missing kit_schema_version {schema!r} (supported: {supported})"
            )
        finding_id = str(metadata.get("finding_id", ""))
        row = known_findings.get(finding_id)
        if row is None:
            raise ValueError(f"unknown finding id {finding_id!r}")
        capture_id = str(metadata.get("capture_id", ""))
        if not capture_id:
            raise ValueError("capture_id is missing")
        if capture_id in existing_capture_ids:
            summary.skipped_duplicates += 1
            return

        relative_output = Path(str(metadata.get("output_file", "")))
        output_path = (root / relative_output).resolve()
        root_resolved = root.resolve()
        if not output_path.is_relative_to(root_resolved):
            raise ValueError("output_file points outside the kit")
        if not output_path.is_file():
            raise ValueError(f"captured output is missing: {relative_output}")
        recorded_hash = str(metadata.get("sha256", ""))
        actual_hash = sha256_file(output_path)
        if not recorded_hash or actual_hash != recorded_hash:
            raise ValueError("captured output SHA-256 does not match metadata")

        command_args = metadata.get("command_args", [])
        if not isinstance(command_args, list) or not all(isinstance(a, str) for a in command_args):
            raise ValueError("command_args must be a list of strings")
        output = output_path.read_text(encoding="utf-8", errors="replace")
        adapter_name = str(metadata.get("adapter", "external"))
        timed_out = bool(metadata.get("timed_out", False))
        exit_code_raw = metadata.get("exit_code")
        exit_code = int(exit_code_raw) if exit_code_raw is not None else None
        observations: dict[str, Any] = {
            "capture_id": capture_id,
            "kit_step_id": metadata.get("step_id", ""),
        }
        review_note = "Imported from a Kali validation kit; reviewer interpretation required."
        adapter = get_adapter(adapter_name)
        if adapter is not None:
            ctx = ExecutionContext(
                finding_id=finding_id,
                asset_id=row["asset_id"],
                engagement_id=self.ws.root.name,
                target=str(metadata.get("target", "")),
                port=int(metadata.get("port", row.get("port", 0)) or 0),
                transport=str(metadata.get("transport", row.get("transport", ""))),
            )
            raw = RawResult(exit_code=exit_code, stdout=output, timed_out=timed_out)
            if adapter_name == "tcp":
                lowered = output.lower()
                raw.port_open = "succeeded" in lowered or "open" in lowered
            parsed = adapter.parse(ctx, raw)
            observations.update(parsed.observations)
            if parsed.note:
                review_note = parsed.note

        evidence_id = uuid.uuid4().hex
        dest_dir = self.ws.evidence_dir / row["asset_id"] / finding_id
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest = dest_dir / f"kali_{evidence_id[:8]}_{output_path.name}"
        shutil.copy2(output_path, dest)
        evidence = Evidence(
            evidence_id=evidence_id,
            finding_id=finding_id,
            engagement_id=self.ws.root.name,
            asset_id=row["asset_id"],
            adapter=adapter_name,
            tool_name=str(metadata.get("tool_name") or adapter_name),
            tool_version=str(metadata.get("tool_version", "")),
            command_args=list(command_args),
            sanitized_command=shlex.join(command_args),
            operator=operator_override or str(metadata.get("operator", "unknown")),
            start_timestamp=str(metadata.get("start_timestamp", "")),
            end_timestamp=str(metadata.get("end_timestamp", "")),
            exit_code=exit_code,
            timed_out=timed_out,
            stdout=output[:20000],
            parsed_observations=observations,
            raw_evidence_path=str(dest),
            sha256=actual_hash,
            sanitization_status="kali_capture_unsanitized",
            review_notes=review_note,
        )
        self.ws.append_evidence(evidence.to_dict())
        self.ws.append_audit_event(
            {
                "event": "kali_evidence_import",
                "finding_id": finding_id,
                "evidence_id": evidence_id,
                "capture_id": capture_id,
                "operator": evidence.operator,
            }
        )
        existing_capture_ids.add(capture_id)
        summary.imported += 1


def _target_for(finding: Finding, asset: dict[str, Any]) -> str:
    raw_ip = finding.host_properties.get("host-ip")
    if isinstance(raw_ip, list):
        raw_ip = raw_ip[0] if raw_ip else ""
    if raw_ip:
        return str(raw_ip)
    addresses = asset.get("ip_addresses", [])
    if addresses:
        return str(addresses[0])
    return str(asset.get("primary_key") or finding.asset_id)


def _hostname_for(finding: Finding, asset: dict[str, Any]) -> str:
    for value in [*asset.get("fqdns", []), *asset.get("hostnames", [])]:
        if value:
            return str(value)
    for key in ("host-fqdn", "host-rdns", "netbios-name"):
        value = finding.host_properties.get(key)
        if isinstance(value, list):
            value = value[0] if value else ""
        if value:
            return str(value)
    return ""


def _step_params(step: RecipeStep, finding: Finding, hostname: str) -> dict[str, Any]:
    params = dict(step.params)
    if hostname:
        params.setdefault("vhost", hostname)
    if params.get("starttls_from"):
        service = finding.service.lower()
        for candidate in ("smtp", "imap", "pop3", "ftp", "xmpp"):
            if candidate in service:
                params["starttls"] = candidate
                break
    if step.adapter == "snmp":
        community = _extract_snmp_community(finding)
        if community:
            params["community"] = community
    return params


def _extract_snmp_community(finding: Finding) -> str:
    text = f"{finding.plugin_name}\n{finding.plugin_output}"
    patterns = [
        r"community string\s*:\s*([^\s,;]+)",
        r"community name\s*:\s*([^\s,;]+)",
        r"community[^\n]*(?:is|was)\s+['\"]?([^\s'\",;]+)",
        r"\(([^()\s]+)\)\s*$",
    ]
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE | re.MULTILINE)
        if match:
            value = match.group(1).strip("'\".()[]")
            if value:
                return value
    return ""


def _specific_manual_description(finding: Finding, description: str) -> str:
    if finding.is_host_level and "ubuntu" in finding.plugin_family.lower():
        package_match = re.search(
            r"Remote package installed\s*:\s*([A-Za-z0-9.+-]+?)(?:_|\s)",
            finding.plugin_output,
            flags=re.IGNORECASE,
        )
        package = package_match.group(1) if package_match else "the reported package"
        return (
            f"{description} On the affected host, have an authorised administrator run "
            f"`dpkg-query -W -f='${{Package}}\\t${{Version}}\\n' {package}` and capture "
            "the output. Compare the installed version with the fixed version in the Nessus output."
        )
    return description


def _step_id(finding_id: str, index: int, adapter: str) -> str:
    clean_finding = re.sub(r"[^A-Za-z0-9_.-]", "_", finding_id)
    clean_adapter = re.sub(r"[^A-Za-z0-9_.-]", "_", adapter)
    return f"{clean_finding}__{index:02d}_{clean_adapter}"


def script_filename(step: KitStep) -> str:
    """A readable script name: ``3-MEDIUM_443-tcp_SSL-Certificate...__01_openssl.sh``.

    ``find-37c3608975b2529abc91d78b__01_openssl.sh`` tells an operator scrolling
    ``scripts/`` nothing about what the script checks or how badly it matters.
    The step id stays inside the file and in the manifest, which is what the
    import actually matches on, so readability here costs no traceability.
    """
    base = finding_basename(
        severity=step.severity,
        target=step.target,
        port=step.port,
        transport=step.transport,
        title=step.title,
    )
    suffix = step.step_id.split("__", 1)[-1]
    return f"{base}__{suffix}.sh"


def _write_lf(path: Path, content: str) -> None:
    # Bash shebangs copied from Windows must use LF or Kali reads "bash\r".
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def _bash(value: str) -> str:
    return shlex.quote(value)


def _scope_note(steps: list[KitStep]) -> str:
    """A commands.md warning for a finding whose target is not plainly runnable.

    The unconfigured case is announced once at the top of the document instead
    of on every finding, so what appears here is always a specific problem.
    """
    for step in steps:
        if step.scope_status == SCOPE_OUT_OF_SCOPE:
            return (
                f"> **OUT OF SCOPE — scripts refuse to run.** {step.scope_reason} "
                "Either add the target to the engagement scope with written "
                "authorisation, or leave this finding for review without evidence."
            )
        if step.scope_status == SCOPE_UNUSABLE_TARGET:
            return (
                f"> **NO COMMAND GENERATED.** {step.scope_reason}"
            )
    return ""


def _step_script(step: KitStep) -> str:
    args = " ".join(_bash(arg) for arg in step.command_args)
    fields = [
        step.step_id,
        step.finding_id,
        step.asset_id,
        step.adapter,
        step.tool,
        step.target,
        str(step.port),
        step.transport,
        step.title,
        step.description,
    ]
    separator = " " + chr(92) + "\n  "
    rendered_fields = separator.join(_bash(value) for value in fields)
    scope_guard = ""
    if step.scope_status == SCOPE_OUT_OF_SCOPE:
        # Quoted as a single argument: target and reason are scanner-derived
        # strings, so they are never pasted raw into the script body.
        refusal = _bash(f"REFUSED (out of scope): {step.target} -- {step.scope_reason}")
        scope_guard = f"""
# The engagement declares an approved scope and this target is outside it.
# Refusing rather than running. Override deliberately with VAPT_ALLOW_OUT_OF_SCOPE=1
# only if you hold written authorisation this tool does not know about.
if [[ "${{VAPT_ALLOW_OUT_OF_SCOPE:-0}}" != "1" ]]; then
  echo {refusal}
  exit 0
fi
"""
    elif step.scope_status == SCOPE_UNCONFIGURED:
        scope_guard = """
# This engagement declares no approved scope, so the tool cannot confirm this
# target is authorised. Confirm before running.
"""

    return f"""#!/usr/bin/env bash
set -uo pipefail

# VAPT_FINDING_ID={step.finding_id}
# VAPT_SCOPE_STATUS={step.scope_status}
# Script filenames are readable rather than id-based, so run-all.sh matches
# --finding against this line instead of against the filename.
{scope_guard}
KIT_ROOT="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/.." && pwd)"
export KIT_ROOT
# shellcheck source=../lib/capture.sh
source "$KIT_ROOT/lib/capture.sh"

capture_step \\
  {rendered_fields} \\
  -- {args}
"""


def _run_all_script() -> str:
    return """#!/usr/bin/env bash
set -uo pipefail

KIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
finding_filter=""
for arg in "$@"; do
  case "$arg" in
    --yes) export VAPT_APPROVE_ALL=1 ;;
    --finding=*) finding_filter="${arg#--finding=}" ;;
  esac
done
if [[ "${1:-}" == "--finding" && -n "${2:-}" ]]; then
  finding_filter="$2"
fi

found=0
for script in "$KIT_ROOT"/scripts/*.sh; do
  [[ -e "$script" ]] || continue
  if [[ -n "$finding_filter" ]]; then
    # Match either the exact finding id recorded inside the script, or any
    # substring of its readable filename -- so `--finding SSL-Certificate`
    # works as well as `--finding find-37c3608975b2529abc91d78b`.
    name="$(basename "$script")"
    if ! grep -q "VAPT_FINDING_ID=$finding_filter$" "$script" \
       && [[ "${name,,}" != *"${finding_filter,,}"* ]]; then
      continue
    fi
  fi
  found=1
  bash "$script"
done

if [[ $found -eq 0 ]]; then
  echo "No executable scripts matched. Review commands.md for manual evidence requests."
fi
echo "Done. Keep the entire kit and copy it back for evidence import."
"""


def _capture_library() -> str:
    # The embedded metadata writer stamps the schema this build produces. The
    # literal is substituted rather than f-string-interpolated because the bash
    # body is full of braces.
    return _CAPTURE_LIBRARY.replace("@KIT_SCHEMA_VERSION@", KIT_SCHEMA_VERSION)


_CAPTURE_LIBRARY = r'''#!/usr/bin/env bash
# Shared evidence-capture function. Generated scripts pass commands as arrays;
# no eval or shell-expanded command string is used.

capture_step() {
  local step_id="$1" finding_id="$2" asset_id="$3" adapter="$4" tool_name="$5"
  local target="$6" port="$7" transport="$8" title="$9" description="${10}"
  shift 10
  [[ "${1:-}" == "--" ]] && shift
  local -a command_argv=("$@")

  echo
  echo "[$finding_id] $title"
  echo "Target: $target  Port: $port/$transport"
  echo "Purpose: $description"
  printf 'Command:'
  printf ' %q' "${command_argv[@]}"
  echo

  if [[ "${VAPT_APPROVE_ALL:-0}" != "1" ]]; then
    read -r -p "Run this authorised validation? [y/N/q] " answer
    case "${answer,,}" in
      y|yes) ;;
      q|quit) echo "Stopped by operator."; exit 0 ;;
      *) echo "Skipped."; return 0 ;;
    esac
  fi

  if ! command -v "${command_argv[0]}" >/dev/null 2>&1; then
    echo "SKIPPED: required tool not found: ${command_argv[0]}"
    return 0
  fi
  for required in python3 sha256sum tee timeout; do
    if ! command -v "$required" >/dev/null 2>&1; then
      echo "ERROR: capture dependency not found: $required"
      return 1
    fi
  done

  local evidence_dir="$KIT_ROOT/evidence"
  mkdir -p "$evidence_dir"
  local stamp capture_id output_path metadata_path
  stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  capture_id="${step_id}_${stamp}_${BASHPID}"
  output_path="$evidence_dir/${capture_id}.txt"
  metadata_path="$evidence_dir/${capture_id}.json"
  local start end exit_code timed_out sha tool_version timeout_seconds
  start="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  timeout_seconds="${VAPT_TIMEOUT_SECONDS:-120}"
  tool_version="$(timeout 5 "${command_argv[0]}" --version 2>&1 | head -n 1 || true)"

  set +e
  timeout --signal=INT "$timeout_seconds" "${command_argv[@]}" </dev/null 2>&1 | tee "$output_path"
  exit_code=${PIPESTATUS[0]}
  set -e
  end="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  timed_out=false
  [[ $exit_code -eq 124 || $exit_code -eq 137 ]] && timed_out=true
  sha="$(sha256sum "$output_path" | awk '{print $1}')"

  python3 - "$metadata_path" "$KIT_ROOT" "$output_path" "$sha" "$capture_id" \
    "$step_id" "$finding_id" "$asset_id" "$adapter" "$tool_name" "$tool_version" \
    "$target" "$port" "$transport" "${USER:-unknown}" "$start" "$end" \
    "$exit_code" "$timed_out" "${command_argv[@]}" <<'PY'
import json
import os
import shlex
import sys

(
    metadata_path, kit_root, output_path, digest, capture_id, step_id,
    finding_id, asset_id, adapter, tool_name, tool_version, target, port,
    transport, operator, start, end, exit_code, timed_out, *command_args
) = sys.argv[1:]
payload = {
    "kit_schema_version": "@KIT_SCHEMA_VERSION@",
    "capture_id": capture_id,
    "step_id": step_id,
    "finding_id": finding_id,
    "asset_id": asset_id,
    "adapter": adapter,
    "tool_name": tool_name,
    "tool_version": tool_version,
    "target": target,
    "port": int(port),
    "transport": transport,
    "operator": operator,
    "start_timestamp": start,
    "end_timestamp": end,
    "exit_code": int(exit_code),
    "timed_out": timed_out.lower() == "true",
    "command_args": command_args,
    "command": shlex.join(command_args),
    "output_file": os.path.relpath(output_path, kit_root),
    "sha256": digest,
}
with open(metadata_path, "w", encoding="utf-8", newline="\n") as handle:
    json.dump(payload, handle, indent=2, sort_keys=True)
    handle.write("\n")
PY

  echo "Captured: $output_path"
  echo "SHA-256: $sha"
  echo "Exit code $exit_code is execution status only; it is not a vulnerability verdict."
  set +e
  return 0
}
'''
